CruGlobal/appbuilder_platform_service

platform/ABObject.js

https://github.com/digi-serve/planning/issues/531

*Fix create trigger of combine fields when import

---

platform/process/tasks/ABProcessTaskServiceAccountingBatchProcessing.js
platform/process/tasks/ABProcessTaskServiceAccountingJEArchive.js

https://github.com/digi-serve/ns_app/issues/26 
https://github.com/digi-serve/ns_app/issues/29

Update Batch and JEArchive processes to use directly SQL scripts

---

platform/process/tasks/ABProcessTaskEmail.js

Add found users to "use account" lookup

Lookup user from user field

---

platform/process/tasks/ABProcessTrigger.js

Are processes don't need them, and creating excess transaction fills up the pool, causing `Timeout acquiring a connection` errors.  See: https://knexjs.org/guide/#acquireconnectiontimeout

remove un-need knex transactions

---

platform/ABProcess.js

Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]: ProcessTask Error: GatewayExclusive : Error: no valid path found {
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]:   instance: {
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]:     uuid: '9d5cfea3-10ff-4457-a0bc-fc6d907d902b',
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]:     processID: '3bbd2774-d3f4-4195-a35a-889f1330a936',
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]:     status: 'created',
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]:     statriggeredBy: 'admin',
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]:     log: [
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]:       'created',
Oct 04 17:02:14 coreos.l2d.biz podman-compose[2872486]: …

[WORKAROUND] Skip add not found task element logging to SITE_PROCESS_INSTANCE to prevent create huge data there

---

platform/ABModel.js

https://github.com/digi-serve/ns_app/issues/147

*Fix is_empty and is_not_empty

---

platform/process/tasks/ABProcessTaskServiceInsertRecord.js

https://github.com/digi-serve/ns_app/issues/157

Fix "Set by previous step data"

---

platform/ABProcess.js
platform/process/tasks/ABProcessTaskServiceGetResetPasswordUrl.js

[fix] the GetResetPasswordURL Task now uses the expected method to lookup a process value.

fix process lookup

---

platform/process/tasks/ABProcessTaskServiceInsertRecord.js

https://github.com/digi-serve/ns_app/issues/224
Adjust `processData` function to return  UUID of recently created record

Make insert-task data available

---

platform/process/tasks/ABProcessTaskServiceInsertRecord.js
platform/ql/ABQLRowPluck.js

https://github.com/digi-serve/ab_service_process_manager/issues/54

Process can insert using many-many

---

platform/ABModel.js
platform/ABObject.js
utils/cleanReturnData.js

Testing out our initial fix for minimizing populated data.
We've been having slow performance and services crashing when trying to JSON.stringify() large data sets.
This set of fixes attempts to reduce the data we return in our populated data so we are encoding and transferring less data overall.

[wip] initial optimization to minimize the data returned for populated fields

---

utils/cleanReturnData.js

[add] further prune the data exchanged between the server and clients

---

utils/cleanReturnData.js

https://github.com/digi-serve/ns_app/issues/262

Fix prune data of connect field that uses custom index

---

platform/process/tasks/ABProcessTrigger.js

Fix error found by sentry: https://appdev-designs.sentry.io/issues/4460436951/events/7d8d46cd521542439a70a8f31d3b37a8/

Fix error reading property of undefined

---

platform/ABObjectApi.js

*Add ABObjectApi

---

platform/ABModelApi.js

+Add ABModelApi

---

platform/ABModelApi.js

- Fetch data of API Object from back end

*Fetch data of API object from back end

---

platform/ABModelApi.js
platform/ABObjectApi.js

https://github.com/digi-serve/ab_service_appbuilder/issues/58
- Implement Key and Secret to API Object

Implement Key and Secret to API Object

---

platform/ABModelQuery.js

https://github.com/digi-serve/ns_app/issues/326
- Add offset and limit statement to pull data of ABQuery

+Add .offset and .limit to pull data comment of ABQuery

---

platform/ABObject.js

- Add file extension validation.

Add file extension validation

---

platform/ABModel.js

https://github.com/digi-serve/ns_app/issues/367
- Include username data of user fields of linked object. They are used to filter in FilterComplex on client

*Pull username data to relation data

---

platform/ABModel.js
policies/ABModelConvertFilterCondition.js

https://github.com/digi-serve/ns_app/issues/384
- Add "checked" and "unchecked" filter conditions

*Fix "checked" and "unchecked" filter conditions

---

platform/ABModel.js

https://github.com/digi-serve/plugin_ABDesigner/issues/242
- Fix .populateMin function
It should have a test case to cover for https://github.com/digi-serve/ab_platform_web/pull/504

*Fix .populateMin function

---

platform/ABModel.js

https://github.com/digi-serve/plugin_ABDesigner/issues/242
- Fix prune relational data
It should have a test case to cover for https://github.com/digi-serve/ab_platform_web/pull/504

*Fix prune relational data

---

platform/ABModel.js

https://github.com/digi-serve/ab_platform_web/issues/471
- Implement sort feature to SelectList field type
https://github.com/digi-serve/kitchensink_app/commit/17a4e2d14d06f809a7c1a48e87224656da822127

+Implement sort feature to SelectList field type

---

platform/ABModel.js

Fix undefined glue

---

platform/ABModel.js

Current date filter

---

platform/ABModel.js
platform/ABProcess.js
platform/process/tasks/ABProcessTrigger.js
utils/cleanReturnData.js

- Add reference between SITE_PROCESS_INSTANCE and SITE_ROWLOG

Add reference between SITE_PROCESS_INSTANCE and SITE_ROWLOG

---

.github/workflows/unit-tests.yml
package-lock.json
package.json
platform/ABProcess.js
test/platform/ABProcess.test.js

https://github.com/digi-serve/ab_service_process_manager/issues/87
- save process instance definition as JSON in a new table
- added unit tests
- will need changes in migration manager to pass e2e

Process Instance Definition

---

platform/ABObject.js
platform/dataFields/ABFieldConnect.js

- Fix pull relational values of 1:1, 1:M type

*Fix pull relational values of 1:1, 1:M type

---

.github/workflows/e2e-tests.yml

- Upgrade actions/upload-artifact

Upgrade actions/upload-artifact

---

platform/ABModel.js

- [fix] filter out null values in our relation work
existing tests are sufficient

[fix] filter out null values in our relation work

---

platform/ABModel.js

- [fix] filter out null values in our relation work
kitchen sink tests are sufficient for this.

Prevent errors when null values end up in relation fields.

---

platform/ABModel.js
policies/ABModelConvertSailsCondition.js

- [wip] include sql LIKE condition in our supported where clauses

Expand our where conditions to include LIKE statements

---

platform/process/tasks/ABProcessElement.js

- [wip] add additional process info to error messages
no additional tests for this at the moment

Add additional information to our process error messages

---

.github/workflows/e2e-tests.yml
platform/dataFields/ABFieldLongText.js
platform/dataFields/ABFieldString.js

https://github.com/digi-serve/ns_app/issues/500
- Fix Remove the white space at the end of the Description text field

Fix Remove the white space at the end of the Description text field

---

platform/process/tasks/ABProcessTaskUserApproval.js

https://github.com/digi-serve/sdc-app/issues/241
https://github.com/digi-serve/sdc-app/issues/241#issuecomment-2395806601
- Fix "by Fields" option of the User Approval process task

*Fix "by Fields" option of the User Approval process task

---

platform/ql/ABQLFind.js
platform/ql/ABQLSetPluck.js

https://github.com/digi-serve/sdc-app/issues/240
- Fix pull data of ABQLSetPluck

*Fix pull data of ABQLSetPluck

---

platform/ql/ABQLSetPluck.js

- Reduce the size of relation data to prevent excessive data in SITE_PROCESS_INSTANCE

Reduce the size of relation data to prevent excessive data in SITE_PROCESS_INSTANCE

---

platform/ql/ABQLSetPluck.js

https://github.com/digi-serve/sdc-app/issues/240
https://team.digiserve.org/main/pl/4b3wkmxqetno9brge6qo3i1mpw
- Fix pluck relation data for the next step

*Fix pluck relation data for the next step

---

ABFactory.js
platform/ABModel.js

https://github.com/digi-serve/ab_platform_web/issues/566
- Add "getUTCDayTimeRange function" to AppBuilder Service
- Adjust "is_cerrent_date" within parseCondition to get a current date from the "getUTCDayTimeRange" function

"Is Current Date" filter on Formula Field doesn't work on server design

---

platform/ABObject.js
platform/dataFields/ABFieldConnect.js
platform/process/ABProcessParticipant.js
platform/process/tasks/ABProcessGatewayExclusive.js
platform/process/tasks/ABProcessTaskEmail.js
platform/process/tasks/ABProcessTaskServiceAccountingBatchProcessing.js
platform/process/tasks/ABProcessTaskServiceAccountingFPClose.js
platform/process/tasks/ABProcessTaskServiceAccountingFPYearClose.js
platform/process/tasks/ABProcessTaskServiceAccountingJEArchive.js
platform/process/tasks/ABProcessTaskServiceCalculate.js
platform/process/tasks/ABProcessTaskServiceGetResetPasswordUrl.js
platform/process/tasks/ABProcessTaskServiceInsertRecord.js
platform/process/tasks/ABProcessTaskServiceQuery.js
platform/process/tasks/ABProcessTaskUserApproval.js
platform/process/tasks/ABProcessTaskUserExternal.js
platform/process/tasks/ABProcessTrigger.js
platform/process/tasks/ABProcessTriggerTimer.js

- [wip] numerous eslint changes
no tests. they are just eslint changes.

Just a bunch of eslint changes

---

platform/ABModelApiNetsuite.js

It seems like NetSuite is using Oracle and does not support some of our SQL method.
- Now fix parsing the sql DATE() and NOW() conditions.
https://github.com/digi-serve/ab_platform_web/pull/603

Fix parsing sql conditions

---

platform/ABModelApiNetsuite.js

- Fix bug cond.skip -> cond.offset.

Fix bug cond.skip -> cond.offset

---

platform/ABModelApiNetsuite.js

- fix query syntax for Netsuite checkbox fields

NetSuite Query Checkbox Fields

---

platform/ABModel.js

https://github.com/digi-serve/ns_app/issues/560
- Add "have_relation" filter condition

+Add "have_relation" filter condition

---

platform/process/tasks/ABProcessTaskSubProcess.js
platform/ql/ABQLFind.js

- Fix getting process in sub process
Related:
https://github.com/digi-serve/ab_platform_web/pull/633

Fix getting process data in subprocess

---

ABFactory.js
platform/mobile/ABMobileViewTimeline.js

These changes are to support the PWA platform's newest additions: Timeline widget and Preloader
- [add] A Timeline widget for our PWA platform

PWA Platform Additions: Timeline and Preloader

---

platform/mobile/ABMobileViewCustom.js

Including the ABMobileViewCustom class to the service framework.
- [add] default Mobile Custom View class

Add the PWA Custom View widget 

---

platform/process/tasks/ABProcessTaskSubProcess.js

*Fix execute the sub process

---

platform/process/tasks/ABProcessTaskServiceInsertRecord.js

*Fix undefined object

---

platform/ABModelApiNetsuite.js

Fix function name bugs

---

platform/process/tasks/ABProcessTaskServiceInsertRecord.js
platform/process/tasks/ABProcessTaskSubProcess.js

- Fix pull data in the insert task which nested subprocess

*Fix pull data in the insert task which nested subprocess

---

platform/ABModel.js

- support sorting by created_at/updated_at column

Support sorting by created_at/updated_at column

---

platform/ABModel.js
platform/dataFields/ABFieldConnect.js

https://github.com/digi-serve/ns_app/issues/597
- Fix unrelate values of M:N connect field

*Fix unrelate values of M:N connect field

---

platform/process/tasks/ABProcessTaskUserForm.js

https://github.com/digi-serve/global-hr-update/issues/219
- Implement the user form task

Implement the user form task

---

ABFactory.js

- [fix] improper reference to nanoid

Fix Improper reference to nanoid

---

platform/ABModelApiNetsuite.js

It turns out it looks like we weren't paying attention to Netsuite's pagination limits on our find operations.
This patch will cause us to query the additional pages until we compile our expected results.
- [fix] make sure we pull paginated responses from Netsuite

Make sure we  Paginate Netsuite's results

---

platform/process/tasks/ABProcessTaskServiceInsertRecord.js

https://github.com/digi-serve/appbuilder_platform_service/security/code-scanning/19
(Note mostly doing this to trigger a new build)
- Fix [Code scanning alerts](https://github.com/digi-serve/appbuilder_platform_service/security/code-scanning) [#19](https://github.com/digi-serve/appbuilder_platform_service/security/code-scanning/19)

remove unneeded code

---

platform/ABModel.js
platform/ABModelApiNetsuite.js

- Fix condition format when process ABQLFind triggered

Fix condition format when process ABQLFind triggered

---

platform/ql/ABQLFind.js

- This make Process condition in_process_value wrong.

This make Process condition in_process_value wrong

---

.github/workflows/pr-merge-release.yml

https://github.com/CruGlobal/appbuilder_platform_service/actions/runs/17571554640/job/49909674365

Fix names of repositories to dispatch to
