CruGlobal/appbuilder_platform_service

platform/ABObject.js

Fixes two issues with scopes:
1. Combining a filtered and unfiltered scope returned filtered data, when the least restrictive scope (unfiltered) should be used. digi-serve/appbuilder_class_core#71
2. Scopes where ignoring the attached objects and only using the filters, giving access to more objects than the scope rules set.
These issues are added as test cases to the kitchensink_app in digi-serve/kitchensink_app#23. The test pass with the changes here.

Fix scopes

---

platform/ABModel.js
platform/process/tasks/ABProcessElement.js
platform/process/tasks/ABProcessTaskServiceCalculate.js
platform/process/tasks/ABProcessTaskServiceInsertRecord.js

Includes commits from #15
Fixes two issues:
- The Insert Task option `use parameter of previous task` was depreciated for query tasks in v1, but v2 was still trying to process data, which gave an error
- Calculate task uses regex based on field labels but did not escape brackets in the label.

Fix process errors

---

platform/ABObject.js

This change fixes the "FATAL ERROR: Javascript heap out of memory" that has been crashing `ab_service_appbuilder` on staging2.
The crash happens consistently for the `admin` user, within one minute after loading the site. Staging2 has a lot of data, so it seems like the `"populate": true` option leads to basically the entire DB being fetched just to check the user's roles and scopes.
I think in general, `"populate": true` should not be used unless care has been taken to limit the amount of data it will fetch.

Fix out-of-memory crash

---

platform/ABModel.js

Reverts digi-serve/appbuilder_platform_service#46
Front-end does expects the populated data in some places. This is breaking some things for the Well, and likely other apps. 
Revert for now, but I think we will need a better long term solution.

Revert "Fix request timeouts"

---

ABBootstrap.js
ABFactory.js

The Production site was generating ER_CON_COUNT_ERROR errors in the Objection(Knex) library.
Every time a definition was edited/created our services would recreate an AB factory.  Each AB factory was creating a NEW Knex connection pool.  This eventually was using up all the mysql connections.
This update will reuse any existing Knex connection pools to reduce the number of open connections being established.
NOTE: our Mysql connections will scale by: `MYSQL_POOL_MAX` x `#Tenants` x `#ServicesThatUseKnex`
So the more tenants we host in the system the more connections that will be used.
If this becomes too much, the next step is to:
- review the Knex code (ABObjectModel) to verify every reference to a DB table is qualified as `tenantID`.`table name`
- then replace the `KnexPool` with a …

[fix] reuse Knex connection pools when ABFactories are recreated

---

platform/dataFields/ABFieldNumber.js

This happens when our current PWA app, sends in data via the Rest methods.

[add] prevent Validation errors if the numeric value is currently a String representation of the number.

---

ABBootstrap.js

- [add] expose the ability to resetDefinitions() from the Factory
In rare cases, a new definition might not be present in a service handler.  If detected, we want the ability for the handler to manually reset the definitions.

[add] expose the ability to resetDefinitions() from the Factory

---

platform/ABModel.js

- *Fix objection warning message
`Feb 02 12:00:29 coreos.l2d.biz podman-compose[163931]: Duplicate relation "Moderator__relation" in a relation expression. You should use "a.[b, c]" instead of "[a.b, a.c]". This will cause an error in objection 2.0`

*Fix objection warning message

---

platform/ABObject.js

In the case of 
1. The current user had no ROLES
2. the current where conditions was `{}`
We would generate a problematic where condition that would error out on the call.  This fixes that by simply not including the given where condition in the case of NO ROLES.
#Release Notes
- [fix] update the scoping changes to not include given scope if there are NO ROLES

Fix Edge Case of Scope Rules being applied

---

platform/ABProcess.js

Noticed this bug while testing on my local system.
- [fix] make sure our ProcessInstances are created when there are connection errors

Retry Process Instance creates on connection errors

---

ABFactory.js
utils/cleanReturnData.js

I'm adding an `.isNil()` utility fn to our ABFactory on all platforms.  Once included, I can use that as an easy check for `null` or `undefined` values in our `core` code.
- [wip] added .isNil() utility to ABFactory

Adding isNil() utility fn to ABFactory

---

platform/ql/ABQLSetPluck.js

A recent update to the ABQLSetPluck task caused it to not gather the connected data correctly.
The main issue was an improper call to `.findAll()` that didn't populate the column.  
- [fix] improper call to .findAll() which doesn't populate our lookup column
I'm too lazy to write a test ... maybe Isaac?

Fix Set Pluck Query task not properly gathering connected Data

---

platform/ABIndex.js
platform/ABObject.js
platform/ABProcess.js
platform/dataFields/ABFieldConnect.js

This is a set of changes as a result of working and viewing the logs.
I'm removing the AB factory from some log dumps.
I'm ensuring Knex migration calls are wrapped in req.retry()
I'm fixing an edge case in the process Trigger where multiple parallel requests of the same trigger can result in creating the same entry.
- [fix] remove the AB factory from our Error messages
- [wip] wrap req.retry() around Knex migration calls
- [fix] edge case when instanceDefinition() would cause ER_DUP_ENTRY
no new tests

Various updates.

---

platform/ABProcess.js
platform/process/tasks/ABProcessTaskUserApproval.js

OK, so not sure why it wasn't working, but we kept getting errors after a process was restarted and needed to lookup its jsonDefinition.  For some reason this code:
```
instance.jsonDefinition = await this.AB.objectProcessDefinition()
.model()
.find({ uuid: instance.definition }, req)[0];
```
would just result in `undefined` 
My guess is that the compiler's would misinterpret the `[0]` reference along with the `await`. 
Who knows.  Instead these changes fix the issue and also adds more error protections in place.
- [fix] make sure the json definitions are properly loaded into a process instance
- [wip] eslint changes
none.  who does these?

Fix the missing json definitions on processes that are restarted.

---

platform/ABProcess.js
platform/process/tasks/ABProcessTaskUserApproval.js
platform/ql/ABQLSetPluck.js

We had been getting NETWORK_PACKET_TOO_LARGE errors.  I think the actual problem was that we had a bug where we were gathering ALL receipts and report items instead of just the ones for our entry.  
However, in the process of trying to reduce the data we were sending and saving as part of the form.io data, I came up with this optimization to only send the fields in our data that were being referenced in our form.io components.
- [wip] reduce the amount of data that is stored in our processData for the formbuilder.io
- [wip] eslint changes
- [wip] take a more aggressive scan of our customList formio entries.

Additional compression of our form.io data

---

platform/ABObject.js
policies/ABModelConvertIsUserMNConditions.js

When you perform an `is_current_user` / `is_not_current_user` condition on a User field that is a `many:many` connection, our code was still expecting the `user` field to be on the table.
However, now our `v2` code treats this as a connection, and we were getting 
```
ER_BAD_FIELD_ERROR: Unknown column 'appbuilder-admin.AB_Projectw.Project Owner' in 'where clause
```
Since they are connections, we can simply convert that particular condition into an `in` / `not_in` condition and our code will handle it properly.
NOTE: this is only for situations where the connection is `many:many`. In the other situations, our current code it sufficient. 
- [fix] convert is_current_user to an IN condition if connection is many:many
- [wip] eslint changes

Fix user many:many condition bug

---

platform/ABModel.js

This is a fix for [ns_app#550](https://github.com/digi-serve/ns_app/issues/550)
- [fix] properly reference index fields in unRelate() operations

Properly reference index fields in unRelate() operations

---

ABFactory.js
package.json
platform/ABModelApiNetsuite.js

Every other platform's ABFactory includes `.jobID()`.  
I'm including it here too for consistency.
- [wip] include jobID() in our ABFactory

Include jobID() in our ABFactory

---

platform/ABModelApiNetsuite.js

The original one didn't display the request history if the current second didn't have any requests.
I changed it to display if any of the past 5 sec had a value.
- [wip] improve the Netsuite Concurrency status display to show the request history if any request in past 5 sec had a value.

Improve the Netsuite Concurrency Status display

---

platform/ABModel.js

Watching the boot up logs on the live `hrupdate` site, I saw this error cropping up:
```
{
"domain": "developer",
"error":
{
"__context":
[
".find().findAll().catch():throw err"
],
"name": "TypeError",
"message": "linkObject.model(...).modelKnex is not a function",
"stack": "TypeError: linkObject.model(...).modelKnex is not a function\n    at /app/AppBuilder/platform/ABModel.js:917:45\n    at Array.forEach (<anonymous>)\n    at ABModel.modelKnexRelation (/app/AppBuilder/platform/ABModel.js:909:21)\n    at MyModel.relationMappings (/app/AppBuilder/platform/ABModel.js:877:25)\n    at getRelationMappings (/app/AppBuilder/node_modules/objection/lib/model/Model.js:919:41)\n    at cachedGet (/app/AppBuilder/node_modules/objection/lib/model/Model.js:867:61)\n    at ceaadeaecd.getRelationMappings …
```

Fix Missing reference to modelKnex()

---

platform/process/tasks/ABProcessTaskUserApproval.js

For User Approval tasks to show the values of a connection field, we need to make sure the `.format` keys is sent. 
- [fix] User Approval tasks need to have the .format key for showing connection data.

User Approval Tasks showing Connection Data

---

platform/ABModelApiNetsuite.js

OK, apparently Netsuite requires `offset` to be a multiple of `limit` when setting the paging parameters.
For normal paging, this isn't much of a problem. However some of our UI widgets ( I'm looking at you "grid" ) can decide to request odd pages where the `offset` isn't a multiple of `limit`.
Just go to the AB Designer, pull up an object table with a Netsuite object, and randomly scroll down to an arbitrary place. There is a good chance you'll see a request with offset=783 and limit=20.
Obviously Netsuite has some harsh things to say in that situation.  But we still want it anyway, so ....
This patch will attempt to find the proper offset/limit boundaries around the actual piece of data we are requesting. Request both of those, and then pull out the actual data we were requested.
- …

Netsuite Paging with non standard offset/limit combinations

---

platform/ABModelApiNetsuite.js

Ever wonder why we weren't getting more than 30 rows of data in our ABDesigner when looking at Netsuite Models?
Well, it is because we were not returning the proper count from our Netsuite get operations.  I mean, It looks like I simply put something in there to "make something work" while I continued working on the actual call to Netsuite, and then I forgot about it.  
Well, here is the actual code that should have been there.
- [fix] this is an efficient method to properly return the total_count of our Netsuite get operations.

Fix the Netsuite .findCount() operations.

---

platform/ABModelApiNetsuite.js

OK, we need to respond with our counts properly when 0 results are returned from our calls.
- [fix] make sure Netsuite Counts work when there are 0 results

Fix Netsuite Counts when there are 0 results

---

platform/ABModelApiNetsuite.js

OK, the last update to make sure our Netsuite objects requested all their data, did so sequentially.
But when there were > 23 different pages of data to pull, this ended up taking a lot of time.
We will try to speed things up, by making all those additional calls in parallel.
- [wip] switch the Paging step to issue all requests in parallel.
- [wip] make sure our populate() code passes along the request object
- [wip] prevent populating data when there are 0 results

Netsuite Paging in parallel

---

ABFactory.js
package.json

Initial Implementation of CSV Packing of our Data.
Currently we have been using json as our exchange format between our client and server.  For for larger data sets, the json format repeats a lot of data for the field names. ex:
```
[ 
{
"firstName": "Neo",
"lastName" : "Andersong",
},
{
"firstName": "Morpheous",
"lastName" : "",
},
{
"firstName": "Trinity",
"lastName" : ""
}
]
```
using csv, we can reduce the repeated column information:
```
firstName,lastName
"Neo","Anderson"
"Morpheous",""
"Trinity",""
```
The larger the dataset, the greater the savings. 
The previous data exchange format was
```
{
data: [{obj1}, {obj2}, ... {objN}],
total_bytes:xx,
}
```
This change now encodes our data in the following format:
```
{
csv_packed:{
data: "csv of primary data",
relations: { …
```

CSV Packing of Data (service platform) 

---

ABFactory.js
platform/ABObjectApi.js
platform/ABSecretManager.js
platform/process/tasks/ABProcessTaskServiceApi.js

- Add API Request Service task to processes
- Add a Secret Manager to handle encryption/decryption of site secrets
No test yet, tested locally.
📝 Not Feature Complete, but enough functionality for webhooks
Requires:
https://github.com/digi-serve/plugin_ABDesigner/pull/300
https://github.com/digi-serve/ab_platform_web/pull/657
https://github.com/digi-serve/ab_service_definition_manager/pull/105
https://github.com/digi-serve/appbuilder_class_core/pull/305

Add API Request Service Task
